### ISSUE TITLE
get results into R

### ISSUE THREAD

**Issue by analytichealth** [stla/findInFiles#1]
Hi, nice package!
Is there any way to get the results of the search into R (data.frame or data.table)?

Here is my try:

```
library(findInFiles)
test <- findInFiles(ext = 'R', pattern = 'my_search_string', depth = NULL, wholeWord = TRUE, root = "/project_folder/")
as.data.frame(test)
```

Thanks

**Comment by stla** [comment]
Hello,

 No, I'm afraid it's not possible. I will think a little more about it but I am pessimistic.

Cheers.

**Comment by analytichealth** [comment]
Ok, no problem. Please let me know if you think of a way. thank you

**Comment by stla** [comment]
Finally I think there's a chance it's possible. You want a dataframe with two columns? A column for the filename and a column for the matched pattern?
But not sure I could handle the colors in the dataframe.

**Comment by stla** [comment]
@analytichealth 

  I've done it! You have to set the option `output = "viewer+dataframe"`. For example:

```
folder <- system.file("example", package = "findInFiles")
fif <- findInFiles("R", "function", root = folder, output = "viewer+dataframe")
FIF2dataframe(fif)
```
This gives the dataframe:
```
                               file line              code
1                        folder/f.R    1 f <- function(x){
2              folder/subfolder/g.R    1 g <- function(y){
3 folder/subfolder/subsubfolder/h.R    1 h <- function(z){
```
And you can type `fif` to get the results in HTML in the RStudio viewer pane.

If you want only the dataframe, option `output = "dataframe"`.

Could you give a try? I would be grateful for the feedback.

To install this version:

`remotes::install_github("stla/findInFiles")`

**Comment by stla** [comment]
On CRAN now. But now it's `tibble`, not `dataframe`.
