### ISSUE TITLE
Shiny app is crashing when depth is not filled

### ISSUE THREAD

**Issue by Marsal-a** [stla/findInFiles#2]
For example after using backspace on the pre-filled one value on depth, the shiny app is crashing. 

This is linked to a reactive behavior on the input[['depth']]

![image](https://github.com/stla/findInFiles/assets/44644237/cecb4177-0005-415c-9cf8-6f02dca043c0)

**Comment by Marsal-a** [comment]
I did propose a fix within the following PR : 
https://github.com/stla/findInFiles/pull/3

**Comment by stla** [comment]
Thanks! Will take a look. I did not work on this package for a while. This is an opportunity to refresh it.

**Comment by Marsal-a** [comment]
Thanks for the update of the app, 
as mentionned in the PR : amazing job thank you

**Comment by stla** [comment]
Thanks @Marsal-a !
