### ISSUE TITLE
Feature Request: Search in multiple file type 

### ISSUE THREAD

**Issue by Marsal-a** [stla/findInFiles#4]
I'm doing a lot of research in our R programs and this findInFiles package really helped me. 
It is very well designed and saved me a lot of time, so thanks for this work;

In my organisation, we use multiple file extensions to code in R : 
- .R
- .Rmd
- .Qmd

Right now, I simply process multiple research changing the extension in the shiny app (or with findInFiles / grepInFiles functions).
I think it could be cool if we could input multiple file extensions at once, as a vector (or with fixed separator in the shinyApp?)

But thats only a cherry on the cake since it does not take too much time launching several researchs.

Adam

**Comment by stla** [comment]
Ok, I've done it. It was easy. Use a comma to separate in the Shiny app. Could you please give a try?

I'm glad that someone is helpful for someone!

**Comment by Marsal-a** [comment]
> Ok, I've done it. It was easy. Use a comma to separate in the Shiny app. Could you please give a try?
> 
> I'm glad that someone is helpful for someone!

Tested it, loved it !
thanks !

Also appreciated the additional options included in the shiny app. I have used extended regex so this was helpfull too !

**Comment by stla** [comment]
Cool. 

The new version of the package is on CRAN now.
